version: 2
jobs:
  build:
    docker:
      - image: circleci/circleci/android:api-28-node8-alpha

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install
          command: yarn install
      
      - save_cache:
          key:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Test
          command: yarn test
          when: always
  
      - run:
          name: Test E2E
          command: yarn test:e2e
          when: always
